name: Send updates to parent repo
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: -main
  pull_request:
    branches: -main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:

  Update_parent_repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Pull latest changes from submodule
      - name: Pull & update submodules
        run: |
          git submodule update --init
          git submodule update --remote

      # Runs a set of commands using the runners shell
      - name: Commit & push changes
        run: |
          git config user.name 'GitHub - Update Submodules'
          git config user.email 'cperez@mistercarwash.com'
          git add Common_submodule_test
          git diff --cached --quiet || git commit -m "Update submodule reference"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
